steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/roamingbuddy-web:latest', '-f', 'packages/web/Dockerfile', '.']
images:
  - 'gcr.io/$PROJECT_ID/roamingbuddy-web:latest'
