steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/roamingbuddy-agents:latest', '-f', 'packages/core/Dockerfile', '.']
images:
  - 'gcr.io/$PROJECT_ID/roamingbuddy-agents:latest'
